### ISSUE TITLE
Error `invalid user_data`

### ISSUE THREAD

**Issue by obibring** [GetStream/stream-analytics-js#16]
I am attempting to use `trackEngagement` within a react-native app:

```js
const React = reaquire('react');
const StreamAnalytics = require('stream-analytics');

class TrackClickEngagement extends React.Component {
  trackClickEngagement = () => {
    const client = new StreamAnalytics({
      apiKey,
      token: this.props.analyticsToken,
    });
    await client.setUser({ id: this.props.userId, alias: 'John Doe' });
    await client.trackEngagement({
      label: 'click',
      score: 5,
      content: { foreign_id: this.props.foreignId }
    }); // <--- This throws Exception
  }
  render() {
    ...
  }
}
```

Invoking `client.trackEngagement()` throws 
```json
{
  "detail": "invalid user_data",
  "status_code": 400,
  "code": 4,
  "exception": "InputException",
  "duration": "0.14ms"
}
```

Any idea why this is happening? It appears to work server-side.

**Comment by tbarbugli** [comment]
perhaps `this.props.userId` is not a string value? can you try to cast that to string and try again?

**Comment by obibring** [comment]
@tbarbugli, I verified that it is indeed a string. I double checked all args and they all appear to be correct.

**Comment by ferhatelmas** [comment]
@obibring closing since it's too old and API already changed. If anything is needed, please ping and will investigate.
