### ISSUE TITLE
natives@1.1.6 is deprecated, consider updating to graceful-fs@4.x (WARN)

### ISSUE THREAD

**Issue by ndrsllwngr** [GetStream/stream-analytics-js#18]
According to npm `natives@1.1.6` is deprecated, maybe consider dropping it and instead update to `graceful-fs@4.x`.

```
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
```

https://www.npmjs.com/package/natives → https://www.npmjs.com/package/graceful-fs

**Comment by mahboubii** [comment]
fixed in #19
