### ISSUE TITLE
async is broken

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/stream-analytics-js#6]

**Comment by tbarbugli** [comment]
client is not correctly initialized with the loading snippet. probably something changed in https://github.com/GetStream/stream-analytics-js/blob/master/src/async.js that does not play well with it

**Comment by ruggi** [comment]
Closing as fixed: https://github.com/GetStream/stream-analytics-js/commit/a3375e6f96f8ec9ee1d4bc3cab0a8b4265c522a4
